[[redirects]]
from = "/index.html"
to = "/"
status = 301
force = true


[[redirects]]
from = "/about.html"
to = "/about"
status = 301
force = true


[[redirects]]
from = "/installs.html"
to = "/"
status = 301
force = true


[[redirects]]
from = "/fullSystemInstalls.html"
to = "/"
status = 301
force = true


[[redirects]]
from = "/installsDetail.html"
to = "/"
status = 301
force = true


[[redirects]]
from = "/products.html"
to = "/products"
status = 301
force = true


[[redirects]]
from = '/testimonials.html'
to= '/media/#reviews'
status = 301
force = true


[[redirects]]
from = '/publications.html'
to= '/media/#publications'
status = 301
force = true


[[redirects]]
from = "/mag_articles/*"
to= '/media/#publications'
status = 301
force = true


[[redirects]]
from = "/plaque50.html"
to= '/media/#publications'
status = 301
force = true


[[redirects]]
from = "/plaque100.html"
to= '/media/#publications'
status = 301
force = true


[[redirects]]
from = "/contact.html"
to = "/contact"
status = 301
force = true


[[redirects]]
from = "/porscheUpgrades.html"
to = "/porsche"
status = 301
force = true


[[redirects]]
from = "/purchase.html"
to = "/porsche/#cup-holder"
status = 301
force = true


[[redirects]]
from = "/installsDetail.html?id=16"
to = "/porsche/#cup-holder"
status = 301
force = true


[[redirects]]
from = "/installsDetail.html:id=17"
to = "/porsche/#subwoofer"
status = 301
force = true


[[redirects]]
from = "/installsDetail.html"
to = "/porsche/#door-pocket-fix"
query = {id = ":id"}
status = 301
force = true


[[redirects]]
from = "/installsDetail.html"
to = "/porsche/#speaker-fix"
query = {id = ":id=43"}
status = 301
force = true